apiVersion: apps/v1
kind: Deployment
metadata:
  name: pm1-azure-homer-deployment
  labels:
    app: pm1-azure-homer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pm1-azure-homer
  template:
    metadata:
      labels:
        app: pm1-azure-homer
    spec:
      containers:
      - name: pm1-azure-homer-container
        image: pm1azure.azurecr.io/pm1-azure-homer-image:v3
        volumeMounts:
        - name: config-volume
          mountPath: /www/assets/config.yml
          subPath: config.yml
      volumes:
      - name: config-volume
        configMap:
          name: my-config-map
          items:
          - key: config.yml
            path: config.yml
